import { MenuItem } from '@/types/menu';
import { TEA, COF, ICE, SHK, JCE } from './imagePool';

export const hotItems: MenuItem[] = [
  // ── المشروبات الساخنة ──────────────────────────────────────────────────────
  { id: 'hd-1',  name: 'شاي',                    description: 'شاي أحمر فاخر ساخن',                         price: 15,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 19.50.11 (2).jpeg' },
  { id: 'hd-2',  name: 'شاي باكيت',              description: 'أكياس شاي عالمية مختارة',                   price: 20,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.12.21 (3).jpeg' },
  { id: 'hd-3',  name: 'شاي كرك',                description: 'شاي هندي بالبهارات العطرية',               price: 25,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.12.21 (4).jpeg', badge: 'Popular' },
  { id: 'hd-4',  name: 'شاي كرك حليب',           description: 'شاي كرك كريمي مع حليب طازج',               price: 45,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.12.22 (4).jpeg', badge: 'Popular' },
  { id: 'hd-5',  name: 'شاي حليب',               description: 'شاي أحمر مع حليب دافئ كريمي',             price: 40,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.12.22 (5).jpeg' },
  { id: 'hd-6',  name: 'ينسون',                  description: 'منقوع الينسون المُهدئ الطبيعي',            price: 20,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.12.22 (6).jpeg' },
  { id: 'hd-7',  name: 'نعناع',                  description: 'نعناع طازج ساخن ومُنعش',                   price: 20,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.19.11 (1).jpeg' },
  { id: 'hd-8',  name: 'كركديه',                 description: 'كركديه طبيعي بلون ياقوتي',                 price: 20,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.26.37.jpeg' },
  { id: 'hd-9',  name: 'قرفة',                   description: 'مشروب القرفة العطري الشرقي',               price: 20,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.27.46.jpeg' },
  { id: 'hd-10', name: 'قرفة حليب',              description: 'قرفة مع الحليب الدافئ الكريمي',            price: 40,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.30.19.jpeg' },
  { id: 'hd-11', name: 'زنجبيل',                 description: 'زنجبيل طبيعي حار ومُنشط',                  price: 20,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 20.30.23.jpeg' },
  { id: 'hd-12', name: 'زنجبيل حليب',            description: 'زنجبيل مع حليب دافئ أصيل',                 price: 40,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.00.51.jpeg' },
  { id: 'hd-13', name: 'ميكس أعشاب',             description: 'خلطة أعشاب طبيعية مختارة',                 price: 35,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.00.52.jpeg' },
  { id: 'hd-14', name: 'ميكس أعشاب بالعسل',      description: 'أعشاب طبيعية مع عسل نحل فاخر',             price: 45,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.00.52.jpeg', badge: "Chef's Choice" },
  { id: 'hd-15', name: 'هوت سيدر',               description: 'عصير تفاح ساخن بالقرفة والتوابل',          price: 40,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.30.39 (2).jpeg' },
  { id: 'hd-16', name: 'سحلب سادة',              description: 'سحلب كريمي بالنشا والعطور الشرقية',        price: 40,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.30.39.jpeg' },
  { id: 'hd-17', name: 'سحلب مكسرات',            description: 'سحلب دافئ مع مكسرات محمصة فاخرة',         price: 55,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.00.55 (4).jpeg', badge: 'Popular' },
  { id: 'hd-18', name: 'سحلب فواكه',             description: 'سحلب دافئ مع فواكه طازجة مختارة',          price: 80,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.31.45.jpeg' },
  { id: 'hd-19', name: 'سحلب مكسرات وفواكه',     description: 'سحلب فاخر بالمكسرات والفواكه معاً',         price: 90,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.31.45.jpeg', badge: 'New' },
  { id: 'hd-20', name: 'هوت شوكليت',             description: 'شوكولاتة بلجيكية ساخنة مع كريمة فاخرة',   price: 50,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.00.55.jpeg' },
  { id: 'hd-21', name: 'هوت اوريو',              description: 'شوكولاتة ساخنة مع بسكويت أوريو',           price: 60,  currency: 'ج.م', category: 'hot-drinks', image: '/images/WhatsApp Image 2026-07-28 at 22.32.55.jpeg', badge: 'New' },

  // ── القهوة ────────────────────────────────────────────────────────────────
  { id: 'cf-1',  name: 'قهوة تركي Single',       description: 'قهوة تركية على الرمل الساخن',             price: 30,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.42.16.jpeg' },
  { id: 'cf-2',  name: 'قهوة تركي Double',       description: 'جرعة مضاعفة من القهوة التركية',            price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.42.16.jpeg', badge: 'Popular' },
  { id: 'cf-3',  name: 'قهوة فرنسية',            description: 'قهوة فرنسية غنية ومُكثَّفة',               price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.45.17.jpeg'},
  { id: 'cf-4',  name: 'قهوة بندق',              description: 'قهوة بنكهة البندق المُحمَّص',               price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.46.51.jpeg' },
  { id: 'cf-5',  name: 'قهوة شوكليت',            description: 'قهوة مع لمسة شوكولاتة داكنة',              price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.53.41 (1).jpeg' },
  { id: 'cf-6',  name: 'قهوة كراميل',            description: 'قهوة بكراميل ناعم محضّر يدوياً',           price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.49.33.jpeg' },
  { id: 'cf-7',  name: 'قهوة نوتيلا',            description: 'قهوة مع نوتيلا الكريمية اللذيذة',          price: 60,  currency: 'ج.م', category: 'coffee', image:'/images/WhatsApp Image 2026-07-28 at 22.52.01.jpeg', badge: 'New' },
  { id: 'cf-8',  name: 'اسبريسو Single',          description: 'إسبريسو مُستخلَص بدقة للكريما المثالية',   price: 35,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.53.41 (2).jpeg' },
  { id: 'cf-9',  name: 'اسبريسو Double',          description: 'جرعة مضاعفة من الإسبريسو الفاخر',         price: 55,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.53.41 (2).jpeg' },
  { id: 'cf-10', name: 'أمريكان هوت',            description: 'إسبريسو بالماء الساخن لنكهة سلسة',         price: 40,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.42.16.jpeg' },
  { id: 'cf-11', name: 'ميكاتو',                 description: 'إسبريسو مع رغوة حليب ناعمة',               price: 60,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.42.16.jpeg' },
  { id: 'cf-12', name: 'كابتشينو',               description: 'إسبريسو وحليب مُبخَّر ورغوة — الكلاسيكية', price: 60,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.56.31.jpeg', badge: 'Popular' },
  { id: 'cf-13', name: 'كابتشينو فلافور',        description: 'كابتشينو بنكهة خاصة مميزة',                price: 70,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.56.31.jpeg' },
  { id: 'cf-14', name: 'كورتادو',                description: 'إسبريسو مع حليب بنسبة متساوية',            price: 60,  currency: 'ج.م', category: 'coffee', image: '/images/Screenshot 2026-07-29 at 5.44.44 AM.png' },
  { id: 'cf-15', name: 'لاتيه',                  description: 'إسبريسو مع حليب مُبخَّر وكريمة خفيفة',     price: 60,  currency: 'ج.م', category: 'coffee', image: '/images/istockphoto-2168005130-612x612.jpg' },
  { id: 'cf-16', name: 'هوت سبانيش لاتيه',       description: 'لاتيه إسباني مع حليب مكثف وعسل',           price: 70,  currency: 'ج.م', category: 'coffee', image: '/images/Screenshot 2026-07-29 at 5.43.52 AM.png', badge: "Chef's Choice" },
  { id: 'cf-17', name: 'فلات وايت',              description: 'إسبريسو مزدوج مع رغوة حليب كالحرير',      price: 60,  currency: 'ج.م', category: 'coffee', image: '/images/istockphoto-2168005130-612x612.jpg' },
  { id: 'cf-18', name: 'الأفوجاتو (Affogato)',   description: 'إسبريسو ساخن فوق آيس كريم فانيليا',       price: 70,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 23.03.35.jpeg', badge: 'New' },
  { id: 'cf-19', name: 'موكا وايت',              description: 'إسبريسو مع شوكولاتة بيضاء وحليب',          price: 65,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 23.05.18.jpeg' },
  { id: 'cf-20', name: 'موكا دارك',              description: 'إسبريسو مع شوكولاتة داكنة وحليب ناعم',     price: 65,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 23.05.18.jpeg' },
  { id: 'cf-21', name: 'نسكافيه بلاك',           description: 'نسكافيه فاخر بدون حليب',                   price: 30,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 23.09.37.jpeg' },
  { id: 'cf-22', name: 'نسكافيه حليب',           description: 'نسكافيه مع حليب طازج دافئ',                price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 23.12.06.jpeg' },
  { id: 'cf-23', name: 'كوفي ميكس ساده',         description: 'خلطة قهوة مميزة بدون حليب',                price: 30,  currency: 'ج.م', category: 'coffee', image: '/images/Screenshot 2026-07-29 at 5.40.35 AM.png' },
  { id: 'cf-24', name: 'كوفي ميكس حليب',         description: 'خلطة قهوة فاخرة مع حليب طازج',             price: 50,  currency: 'ج.م', category: 'coffee', image: '/images/Screenshot 2026-07-29 at 5.42.14 AM.png' },
  { id: 'cf-25', name: 'كوفي V60',               description: 'قهوة مُصفَّاة بتقنية V60 الاحترافية',       price: 40,  currency: 'ج.م', category: 'coffee', image: '/images/WhatsApp Image 2026-07-28 at 22.00.56 (2).jpeg' },

  // ── القهوة الباردة ────────────────────────────────────────────────────────
  { id: 'ic-1',  name: 'آيس لاتيه',              description: 'لاتيه مُبرَّد مع حليب بارد ناعم',           price: 75,  currency: 'ج.م', category: 'ice-coffee', image: ICE[1], badge: 'Popular' },
  { id: 'ic-2',  name: 'آيس سبانيش لاتيه',       description: 'لاتيه إسباني بارد مع حليب مُكثَّف',        price: 80,  currency: 'ج.م', category: 'ice-coffee', image: ICE[1], badge: "Chef's Choice" },
  { id: 'ic-3',  name: 'فرابيه',                 description: 'قهوة مثلجة مخفوقة مع كريمة هوائية',       price: 65,  currency: 'ج.م', category: 'ice-coffee', image: ICE[2] },
  { id: 'ic-4',  name: 'فرابتشينو',              description: 'فرابتشينو فاخر مع كريمة وتوبينج',           price: 75,  currency: 'ج.م', category: 'ice-coffee', image: ICE[2], badge: 'Popular' },
  { id: 'ic-5',  name: 'آيس موكا',               description: 'إسبريسو بارد مع شوكولاتة داكنة',           price: 80,  currency: 'ج.م', category: 'ice-coffee', image: ICE[0] },
  { id: 'ic-6',  name: 'آيس امريكان كوفي',       description: 'إسبريسو مُبرَّد فوق الثلج',                price: 60,  currency: 'ج.م', category: 'ice-coffee', image: ICE[0] },
  { id: 'ic-7',  name: 'ايس V60',                description: 'قهوة V60 مُبرَّدة بنكهة نقية',             price: 60,  currency: 'ج.م', category: 'ice-coffee', image: ICE[3] },

  // ── ميلك شيك ─────────────────────────────────────────────────────────────
  { id: 'ms-1',  name: 'فانيلا',                 description: 'ميلك شيك كريمي بالفانيليا الطبيعية',       price: 75,  currency: 'ج.م', category: 'milk-shake', image: SHK[0] },
  { id: 'ms-2',  name: 'مانجو',                  description: 'ميلك شيك مانجو استوائي طازج',              price: 75,  currency: 'ج.م', category: 'milk-shake', image: SHK[3] },
  { id: 'ms-3',  name: 'فراوله',                 description: 'ميلك شيك فراولة وردي لا يُقاوَم',         price: 75,  currency: 'ج.م', category: 'milk-shake', image: SHK[0], badge: 'Popular' },
  { id: 'ms-4',  name: 'شوكلت',                  description: 'ميلك شيك شوكولاتة داكنة غنية',            price: 75,  currency: 'ج.م', category: 'milk-shake', image: SHK[1] },
  { id: 'ms-5',  name: 'بطيخ',                   description: 'ميلك شيك بطيخ منعش بلون أحمر',            price: 80,  currency: 'ج.م', category: 'milk-shake', image: SHK[2] },
  { id: 'ms-6',  name: 'كيوي',                   description: 'ميلك شيك كيوي أخضر منعش',                 price: 80,  currency: 'ج.م', category: 'milk-shake', image: SHK[2] },
  { id: 'ms-7',  name: 'باشن فروت',              description: 'ميلك شيك باشن فروت استوائي',               price: 80,  currency: 'ج.م', category: 'milk-shake', image: SHK[3] },
  { id: 'ms-8',  name: 'بلو بيري',               description: 'ميلك شيك توت أزرق غني المذاق',            price: 80,  currency: 'ج.م', category: 'milk-shake', image: SHK[0] },
  { id: 'ms-9',  name: 'ميكس بيري',              description: 'ميلك شيك خليط التوت المتنوع',              price: 80,  currency: 'ج.م', category: 'milk-shake', image: SHK[2] },
  { id: 'ms-10', name: 'تفاح أخضر',              description: 'ميلك شيك تفاح أخضر منعش فريد',            price: 80,  currency: 'ج.م', category: 'milk-shake', image: SHK[2] },
  { id: 'ms-11', name: 'أوريو',                  description: 'ميلك شيك أوريو كريمي مع بسكويت',          price: 85,  currency: 'ج.م', category: 'milk-shake', image: SHK[1], badge: 'Popular' },
  { id: 'ms-12', name: 'نوتيلا',                 description: 'ميلك شيك نوتيلا بالشوكولاتة والبندق',     price: 85,  currency: 'ج.م', category: 'milk-shake', image: SHK[1] },
  { id: 'ms-13', name: 'لوتس',                   description: 'ميلك شيك لوتس بكراميله الشهير',           price: 85,  currency: 'ج.م', category: 'milk-shake', image: SHK[0] },
  { id: 'ms-14', name: 'بستاشيو',                description: 'ميلك شيك فستق حلبي فاخر',                 price: 90,  currency: 'ج.م', category: 'milk-shake', image: SHK[3] },
  { id: 'ms-15', name: 'سنيكرز',                 description: 'ميلك شيك سنيكرز بالشوكولاتة والكراميل',  price: 90,  currency: 'ج.م', category: 'milk-shake', image: SHK[1] },
  { id: 'ms-16', name: 'جلاكسي',                 description: 'ميلك شيك جلاكسي بنكهة كريمية راقية',     price: 90,  currency: 'ج.م', category: 'milk-shake', image: SHK[1] },

  // ── العصائر الطازجة ──────────────────────────────────────────────────────
  { id: 'fj-1',  name: 'ليمون فريش',             description: 'ليمون طازج مضغوط يدوياً',                 price: 40,  currency: 'ج.م', category: 'fresh-juice', image: JCE[2] },
  { id: 'fj-2',  name: 'ليمون نعناع فريش',       description: 'ليمون طازج مع نعناع منعش',                price: 45,  currency: 'ج.م', category: 'fresh-juice', image: JCE[2], badge: 'Popular' },
  { id: 'fj-3',  name: 'عناب',                   description: 'عصير عناب طبيعي مُرطب',                   price: 40,  currency: 'ج.م', category: 'fresh-juice', image: JCE[3] },
  { id: 'fj-4',  name: 'مانجو',                  description: 'عصير مانجو استوائي طازج',                  price: 55,  currency: 'ج.م', category: 'fresh-juice', image: JCE[0] },
  { id: 'fj-5',  name: 'مانجو حليب',             description: 'عصير مانجو مع حليب طازج كريمي',           price: 60,  currency: 'ج.م', category: 'fresh-juice', image: JCE[0] },
  { id: 'fj-6',  name: 'فراوله',                 description: 'عصير فراولة طازجة بلون وردي',             price: 55,  currency: 'ج.م', category: 'fresh-juice', image: JCE[3] },
  { id: 'fj-7',  name: 'فراوله حليب',            description: 'فراولة مع حليب طازج ناعم',                price: 60,  currency: 'ج.م', category: 'fresh-juice', image: JCE[0] },
  { id: 'fj-8',  name: 'جوافه',                  description: 'عصير جوافة استوائي طازج',                  price: 55,  currency: 'ج.م', category: 'fresh-juice', image: JCE[3] },
  { id: 'fj-9',  name: 'جوافه حليب',             description: 'جوافة مع حليب في مزيج كريمي',             price: 60,  currency: 'ج.م', category: 'fresh-juice', image: JCE[0] },
  { id: 'fj-10', name: 'موز حليب',               description: 'موز طازج مع حليب كريمي سميك',             price: 60,  currency: 'ج.م', category: 'fresh-juice', image: JCE[3], badge: 'Popular' },
  { id: 'fj-11', name: 'بلح حليب',               description: 'بلح طبيعي مع حليب — نكهة شرقية',          price: 70,  currency: 'ج.م', category: 'fresh-juice', image: JCE[3] },
  { id: 'fj-12', name: 'كيوي',                   description: 'عصير كيوي أخضر طازج',                     price: 70,  currency: 'ج.م', category: 'fresh-juice', image: JCE[2] },
  { id: 'fj-13', name: 'كيوي حليب',              description: 'كيوي مع حليب في تناغم كريمي',             price: 80,  currency: 'ج.م', category: 'fresh-juice', image: JCE[2] },
  { id: 'fj-14', name: 'كنتالوب',                description: 'عصير شمام ناضج بنكهة حلوة',               price: 60,  currency: 'ج.م', category: 'fresh-juice', image: JCE[0] },
  { id: 'fj-15', name: 'برتقال',                 description: 'عصير برتقال طازج مضغوط يدوياً',           price: 55,  currency: 'ج.م', category: 'fresh-juice', image: JCE[1] },
  { id: 'fj-16', name: 'أفوكادو',                description: 'عصير أفوكادو كريمي غني بالفيتامينات',     price: 100, currency: 'ج.م', category: 'fresh-juice', image: JCE[3] },
  { id: 'fj-17', name: 'أفوكادو عسل ومكسرات',   description: 'أفوكادو مع عسل نحل ومكسرات متنوعة',       price: 130, currency: 'ج.م', category: 'fresh-juice', image: JCE[3], badge: "Chef's Choice" },

  // ── ميكس فريش ────────────────────────────────────────────────────────────
  { id: 'mf-1',  name: 'فلوريدا',                description: 'مزيج فريش استوائي بنكهة شمسية',           price: 70,  currency: 'ج.م', category: 'mix-fresh', image: JCE[0] },
  { id: 'mf-2',  name: 'مانجو بيتش',             description: 'مانجو مع خوخ طازج في مزيج صيفي',          price: 70,  currency: 'ج.م', category: 'mix-fresh', image: JCE[0] },
  { id: 'mf-3',  name: 'باشن فروت',              description: 'باشن فروت استوائي فريد المذاق',            price: 70,  currency: 'ج.م', category: 'mix-fresh', image: JCE[3] },
  { id: 'mf-4',  name: 'مانجو هواي',             description: 'مانجو هاواي استوائي بنكهة الجزر',          price: 70,  currency: 'ج.م', category: 'mix-fresh', image: JCE[0] },
  { id: 'mf-5',  name: 'جي سي',                  description: 'مانجو+فراوله+كيوي+موز+فانيلا+بلو بيري',  price: 90,  currency: 'ج.م', category: 'mix-fresh', image: JCE[3], badge: "Chef's Choice" },
  { id: 'mf-6',  name: 'بينا كولادا',            description: 'اناناس+جوز هند+فانيلا — نكهة شاطئية',    price: 85,  currency: 'ج.م', category: 'mix-fresh', image: JCE[0] },
  { id: 'mf-7',  name: 'سكاي مود',               description: 'مزيج سكاي 7 الخاص — تجربة استثنائية',     price: 100, currency: 'ج.م', category: 'mix-fresh', image: JCE[3], badge: 'New' },
];
